include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

# Only start pipelines on Merge Requests, the default branch, and tags
workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_MERGE_REQUEST_IID
      when: always
    - if: $CI_COMMIT_TAG
      when: always
    - when: never

stages:
  - test
  - deploy

default:
  tags:
    - oss
  retry:
    max: 2
    when:
      - unknown_failure
      - api_failure
      - stuck_or_timeout_failure
      - runner_system_failure

#################################
##            RULES            ##
#################################

.on_merge_request_and_merged_events:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

#################################
##            BUILD            ##
#################################

pages:
  image: node:lts
  stage: deploy
  variables:
    PAGES_PREFIX: ""
  pages:
    path_prefix: "$PAGES_PREFIX"
  environment:
    name: "Docs ${PAGES_PREFIX}"
    url: "${CI_PAGES_URL}/${PAGES_PREFIX}"
  before_script:
    - npm install --legacy-peer-deps
  script:
    - npm run build
    - mkdir public
    - mv build/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        PAGES_PREFIX: "mr-$CI_MERGE_REQUEST_IID"
        DOCS_BASE_URL: /martian-cloud/tharsis/$CI_PROJECT_NAME/mr-$CI_MERGE_REQUEST_IID/

#################################
##            SAST             ##
#################################

gemnasium-dependency_scanning:
  variables:
    DS_INCLUDE_DEV_DEPENDENCIES: "false"
  rules:
    - !reference [.on_merge_request_and_merged_events, rules]

semgrep-sast:
  rules:
    - !reference [.on_merge_request_and_merged_events, rules]

secret_detection:
  rules:
    - !reference [.on_merge_request_and_merged_events, rules]
