default:
  tags:
    - oss
  retry:
    max: 2
    when:
      - unknown_failure
      - api_failure
      - stuck_or_timeout_failure
      - runner_system_failure

publish docs:
  image: node:lts
  before_script:
    - npm install --legacy-peer-deps
  script:
    - npm run build
    - mkdir public
    - mv build/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
