// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion
const { themes } = require('prism-react-renderer');
const lightCodeTheme = themes.github;
const darkCodeTheme = themes.nightOwl;
const defaultURI = "http://localhost:3000";

const fs = require('fs');
const path = require('path');

// Copies remote markdown files to the build output for the markdown source plugin.
// Add directories here to automatically include all .md files within them.
const remoteDirs = [
    'docs/provider/data-sources',
    'docs/provider/resources',
];
// Add individual files here.
const remoteFiles = [
    'docs/cli/tharsis/commands.md',
];

function copyRemoteMarkdown() {
    return {
        name: 'copy-remote-markdown',
        async postBuild({ outDir }) {
            for (const file of remoteFiles) {
                const src = path.join(__dirname, file);
                const dest = path.join(outDir, file.replace('docs/', ''));
                if (fs.existsSync(src)) fs.copyFileSync(src, dest);
            }
            for (const dir of remoteDirs) {
                const dirPath = path.join(__dirname, dir);
                if (!fs.existsSync(dirPath)) continue;
                for (const file of fs.readdirSync(dirPath).filter(f => f.endsWith('.md'))) {
                    const src = path.join(dirPath, file);
                    const dest = path.join(outDir, dir.replace('docs/', ''), file);
                    fs.mkdirSync(path.dirname(dest), { recursive: true });
                    fs.copyFileSync(src, dest);
                }
            }
        },
    };
}

function cleanProviderDoc(filename, content) {
    return {
        filename,
        content: content
            .replace(/page_title:\s*"(.+?)\s*(?:-\s*terraform-provider-tharsis)?"/, (_, title) => {
                return `title: "${title.replace(/\s*(?:\()?(?:Data Source|Resource)(?:\))?$/, '')}"`;
            })
            .replace(/^subcategory:.*\n/m, '')
            .replace(/^# generated by.*\n/m, '')
            .replace(/^description: \|-\n\s+.+\n/m, '')
            .replace(/^(#\s+\S+)\s+(?:\()?(?:Data Source|Resource)(?:\))?\s*$/m, '$1'),
    };
}

/** @type {import('@docusaurus/types').Config} */
const config = {
    title: "Tharsis",
    titleDelimiter: "🚀",
    tagline: "Open-source Terraform Platform",
    url: String(process.env.DOCS_URL || defaultURI),
    baseUrl: String(process.env.DOCS_BASE_URL || "/"),
    onBrokenLinks: "throw",
    // Terraform provider docs use <a id=""> anchors that Docusaurus can't resolve.
    // Warnings about broken anchors in /provider/ pages are expected.
    onBrokenAnchors: "warn",

    markdown: {
        mermaid: true,
        hooks: {
            onBrokenMarkdownLinks: "warn",
        },
    },

    favicon: "img/tharsis-logo.svg",

    headTags: [
        {
            tagName: 'script',
            attributes: { type: 'application/ld+json' },
            innerHTML: JSON.stringify({
                '@context': 'https://schema.org',
                '@type': 'SoftwareApplication',
                name: 'Tharsis',
                applicationCategory: 'DeveloperApplication',
                description: 'Open-source, self-hosted Terraform platform for managing infrastructure deployments, state, and workspaces.',
                url: 'https://tharsis.martian-cloud.io',
                operatingSystem: 'Linux, macOS, Windows',
            }),
        },
    ],

    // Even if you don't use internalization, you can use this field to set useful
    // metadata like html lang. For example, if your site is Chinese, you may want
    // to replace "en" with "zh-Hans".
    i18n: {
        defaultLocale: "en",
        locales: ["en"],
    },

    themes: ['@docusaurus/theme-mermaid'],

    plugins: [
        'docusaurus-markdown-source-plugin',
        copyRemoteMarkdown,
        require.resolve('./src/plugins/announcementBarPlugin'),
        [
            require.resolve("@easyops-cn/docusaurus-search-local"),
            /** @type {import("@easyops-cn/docusaurus-search-local").PluginOptions} **/
            {
                indexBlog: true,
                docsRouteBasePath: "/",
                hashed: true
            }
        ],
        [
            "docusaurus-plugin-remote-content",
            {
                name: "tharsis-cli-generated-markdown",
                sourceBaseUrl: "https://gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-cli/-/raw/main/docs/",
                outDir: "docs/cli/tharsis",
                documents: ["commands.md"],
            },
        ],
        [
            "docusaurus-plugin-remote-content",
            {
                name: "tharsis-provider-docs",
                sourceBaseUrl: "https://raw.githubusercontent.com/martian-cloud/terraform-provider-tharsis/main/docs/",
                outDir: "docs/provider",
                documents: Promise.all(
                    ["data-sources", "resources"].map(dir =>
                        fetch(`https://api.github.com/repos/martian-cloud/terraform-provider-tharsis/contents/docs/${dir}`)
                            .then(r => r.json())
                            .then(items => items.filter(i => i.name.endsWith(".md")).map(i => `${dir}/${i.name}`))
                    )
                ).then(res => res.flat()),
                modifyContent: cleanProviderDoc,
                performCleanup: false,
            },
        ],
    ],

    presets: [
        [
            "classic",
            /** @type {import('@docusaurus/preset-classic').Options} */
            ({
                docs: {
                    routeBasePath: "/",
                    sidebarPath: require.resolve("./sidebars.js"),
                    showLastUpdateTime: true,
                    showLastUpdateAuthor: true,
                    editUrl: "https://gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-docs/-/edit/main/",
                },
                blog: {
                    routeBasePath: "/blog",
                    blogSidebarCount: 0,
                    onInlineAuthors: 'ignore',
                },
                theme: {
                    customCss: require.resolve("./src/css/custom.css"),
                },
            }),
        ],
    ],

    themeConfig:
        /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
        ({
            // SEO metadata
            metadata: [
                {name: 'description', content: 'Tharsis is an enterprise scale Terraform platform that offers a complete solution for managing your Terraform deployments, state and workspaces.'},
                {name: 'keywords', content: 'terraform, infrastructure as code, devops, automation, enterprise, platform, state management, open source'},
                {name: 'author', content: 'Infor'},
                {property: 'og:image', content: '/img/tharsis-logo.svg'},
            ],
            navbar: {
                title: "Tharsis",
                logo: {
                    alt: "Tharsis Logo",
                    src: "img/tharsis-logo.svg",
                },
                hideOnScroll: true,
                items: [
                    {
                        to: "/intro",
                        position: "left",
                        label: "Docs",
                    },
                    {
                        to: 'blog',
                        label: 'Blog',
                        position: 'left'
                    },
                    {
                        href: "https://gitlab.com/groups/infor-cloud/martian-cloud/tharsis",
                        position: "right",
                        className: "header-gitlab-link",
                        "aria-label": "GitLab repository",
                        title: "View on GitLab",
                    },
                ],
            },
            colorMode: {
                respectPrefersColorScheme: true,
            },
            docs: {
                sidebar: {
                    hideable: true,
                    autoCollapseCategories: true,
                },
            },
            footer: {
                style: "dark",
                logo: {
                    alt: "Tharsis Logo",
                    src: "img/tharsis-logo.svg",
                    href: "https://gitlab.com/groups/infor-cloud/martian-cloud/tharsis",
                    target: "_blank",
                    style: { marginTop: 0 },
                    width: 100,
                    height: 100,
                },
                links: [
                    {
                        title: "Get Started",
                        items: [
                            {
                                label: "Introduction",
                                to: "/intro",
                            },
                            {
                                label: "Quickstart",
                                to: "/quickstart",
                            },
                        ],
                    },
                    {
                        title: "CLI",
                        items: [
                            {
                                label: "MCP Server",
                                to: "/cli/tharsis/mcp",
                            },
                            {
                                label: "Terraform",
                                to: "/cli/terraform/usage",
                            },
                            {
                                label: "Tharsis",
                                to: "/cli/tharsis/intro",
                            },
                        ],
                    },
                    {
                        title: "Deployments",
                        items: [
                            {
                                label: "Module Sources",
                                to: "/deployments/module_sources",
                            },
                            {
                                label: "CLI",
                                to: "/deployments/cli",
                            },
                            {
                                label: "VCS",
                                to: "/deployments/vcs",
                            },
                            {
                                label: "CI/CD",
                                to: "/deployments/cicd",
                            },
                        ],
                    },
                    {
                        title: "Follow Infor",
                        items: [
                            {
                                label: "Facebook",
                                href: "https://facebook.com/infor",
                            },
                            {
                                label: "Instagram",
                                href: "https://instagram.com/infor",
                            },
                            {
                                label: "LinkedIn",
                                href: "https://www.linkedin.com/company/infor",
                            },
                            {
                                label: "Twitter",
                                href: "https://twitter.com/infor",
                            },
                            {
                                label: "YouTube",
                                href: "https://www.youtube.com/c/InforGlobal",
                            },
                        ],
                    },
                ],
                copyright: `Copyright © ${new Date().getFullYear()} Infor. All rights reserved.`,
            },
            prism: {
                theme: lightCodeTheme,
                darkTheme: darkCodeTheme,

                // Add any additional languages go here for syntax highlighting.
                additionalLanguages: ["hcl", "json", "bash", "powershell", "graphql"],
            },
        }),
};

module.exports = config;
