/**
Any new items added to the docs will need to be updated
in this sidebar as well or else they won't show up.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    "intro",
    "quickstart",
    {
      type: "category",
      label: "Setup",
      link: {
        type: "generated-index",
        description: "Setup guides for Tharsis API, CLI and Docker.",
        keywords: [
          "setup",
          "install",
          "installation",
          "configure",
          "configuration",
        ],
        slug: "setup",
      },
      items: ["setup/api", "setup/cli", "setup/docker"],
    },
    {
      type: "category",
      label: "Basic Guides",
      link: {
        type: "generated-index",
        description:
          "A general summary and guide to different Tharsis functionalities",
        keywords: ["tharsis", "overview", "deployments", "guide"],
        slug: "guides",
      },
      items: [
        "guides/groups",
        "guides/workspaces",
        "guides/variables",
        "guides/service_accounts",
        "guides/managed_identities",
        "guides/memberships",
        "guides/runs",
        "guides/runner_agents",
        "guides/vcs_providers",
        "guides/federated_registries",
        "guides/module_registry",
        "guides/provider_registry",
        "guides/provider_mirror",
        "guides/resource_identifiers",
        "guides/mcp",
      ],
    },
    {
      type: "category",
      label: "Deployments",
      link: {
        type: "generated-index",
        description: "Guides for deploying Terraform modules with Tharsis.",
        keywords: ["deployments", "private", "registry", "terraform", "module"],
        slug: "deployments",
      },
      items: [
        "deployments/module_sources",
        "deployments/cli",
        "deployments/vcs",
        "deployments/cicd",
      ],
    },
    {
      type: "category",
      label: "Command Line Interface (CLI)",
      link: {
        type: "generated-index",
        description: "Using Tharsis and Terraform CLI",
        keywords: [
          "command line",
          "command",
          "command line interface",
          "cli",
          "shell",
        ],
        slug: "cli",
      },
      items: [
        {
          type: "category",
          label: "Tharsis",
          link: {
            type: "generated-index",
            description: "Everything about the Tharsis CLI",
            keywords: [
              "cli",
              "command",
              "command line interface",
              "shell",
              "tharsis cli",
              "tharsis",
            ],
            slug: "cli/tharsis",
          },
          items: [
            "cli/tharsis/intro",
            "cli/tharsis/commands",
            "cli/tharsis/mcp",
          ],
        },
        {
          type: "category",
          label: "Terraform",
          link: {
            type: "generated-index",
            description: "Using Terraform CLI with Tharsis",
            keywords: [
              "cli",
              "command",
              "command line interface",
              "shell",
              "terraform cli",
              "terraform",
            ],
            slug: "cli/terraform",
          },
          items: ["cli/terraform/usage"],
        },
      ],
    },
    {
      type: "category",
      label: "Tharsis Terraform Provider",
      link: {
        type: "generated-index",
        description: "Guide for Tharsis Terraform Provider.",
        keywords: ["terraform", "tharsis", "provider"],
        slug: "provider",
      },
      items: [
        "provider/intro",
        {
          type: "category",
          label: "Data Sources",
          items: [{ type: "autogenerated", dirName: "provider/data-sources" }],
        },
        {
          type: "category",
          label: "Resources",
          items: [{ type: "autogenerated", dirName: "provider/resources" }],
        },
      ],
    },
  ],
};

module.exports = sidebars;
